
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gomboard
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.springframework.boot.autoconfigure: ERROR
