
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gomboard
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      jwt-key:
        host: localhost
        port: 6379
        database: 0
      user-jwt:
        host: localhost
        port: 6380
        database: 1

logging:
  level:
    org.springframework.boot.autoconfigure: ERROR
